name: Monitor Fly.io App

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH

    - name: Authenticate with Fly.io
      run: fly auth whoami
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Check machine status
      run: |
        STATUS=$(fly machines list --app paycut-reminder-bot --json | jq -r '.[0].state')
        echo "Status: $STATUS"
        if [ "$STATUS" != "started" ]; then
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content":"🚨 Fly.io app is not running!"}' ${{ secrets.DISCORD_MONITOR_WEBHOOK }}
          exit 1
        fi
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
